# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.163.1/containers/go/.devcontainer/base.Dockerfile

FROM golang:1.18-alpine

RUN apk add --no-cache build-base git bash
